const LOGIN_REQUEST = '@@auth/LOGIN_REQUEST';
const LOGIN_SUCCESS = '@@auth/LOGIN_SUCCESS';
const LOGIN_FAILURE = '@@auth/LOGIN_FAILURE';

const TOKEN_REQUEST = '@@auth/TOKEN_REQUEST';
const TOKEN_RECEIVED = '@@auth/TOKEN_RECEIVED';
const TOKEN_FAILURE = '@@auth/TOKEN_FAILURE';

const ACCOUNT_INFO_STORE = 'ACCOUNT_INFO_STORE';

const ACCOUNT_INFO_REQUEST = '@@auth/ACCOUNT_INFO_REQUEST';
const ACCOUNT_INFO_SUCCESS = '@@auth/ACCOUNT_INFO_SUCCESS';
const ACCOUNT_INFO_FAILURE = '@@auth/ACCOUNT_INFO_FAILURE';

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  TOKEN_REQUEST,
  TOKEN_RECEIVED,
  TOKEN_FAILURE,
  ACCOUNT_INFO_STORE,
  ACCOUNT_INFO_REQUEST,
  ACCOUNT_INFO_SUCCESS,
  ACCOUNT_INFO_FAILURE
};
