version: '3.7'

services:
  traefik:
        image: traefik # The official Traefik docker image
        command: --api --docker # Enables the web UI and tells Traefik to listen to docker
        ports:
            - "80:80"     # The HTTP port
            - "443:443"     # The HTTPS port
            - "8080:8080" # The Web UI (enabled by --api)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/traefik.toml
            - ./traefik/acme.json:/acme.json
        networks:
            - master
        labels:
            - "traefik.frontend.rule=Host:monitor.${BASE_URL:-localhost}" # add another rule with ";Host:host"
            - "traefik.enable=true"
            - "traefik.frontend.auth.basic=nimda:$$apr1$$/2Ca8pGP$$fOtX7Sq6EwS8KxPAOYGO1/"
            - "traefik.port=8080"
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_db
    networks:
      - master
    labels:
      - "traefik.enable=false"
  api:
    build: ./api
    command: bash -c "python manage.py makemigrations api && python manage.py migrate  && python manage.py makemigrations && python manage.py migrate  && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - master

    labels:
      - "traefik.backend=api"
      - "traefik.docker.network=${network_name:-masternetwork}"
      - "traefik.frontend.rule=Host:api.${BASE_URL:-localhost}" # add another rule with ";Host:host"
      - "traefik.enable=true"
      - "traefik.port=8000"
  
  frontend:
    build:
            context: ./frontend
            args:
                - ENV=${ENV:-development}
                - BASE_URL=${BASE_URL:-localhost}
                - API_BASE_URL=${API_URL:-api.localhost}
                - HTTP=${HTTP:-http}
    command: ["npm","run", "start:prod"]
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
            # Needed for haproxy in swarm
            - SERVICE_PORTS=3000
    networks:
      - master
    labels:
      - "traefik.backend=ui"
      - "traefik.docker.network=${network_name:-masternetwork}"
      - "traefik.frontend.rule=Host:${BASE_URL:-localhost}" # add another rule with ";Host:host"
      - "traefik.enable=true"
      - "traefik.port=3000"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-mazurbeam@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    labels:
      - "traefik.backend=api"
      - "traefik.docker.network=${network_name:-masternetwork}"
      - "traefik.frontend.rule=Host:pgadmin.${BASE_URL:-localhost}" # add another rule with ";Host:host"
      - "traefik.enable=true"
      - "traefik.port=5050"
    networks:
      - master
    restart: unless-stopped

networks:
  # Network mostly needed for swarm
  # Set to bridge to test locally and have ports be outside accessible
  master:
    driver: overlay
    name: "${network_name:-masternetwork}"

volumes:
  node-modules:
  postgres_data:
  pgadmin:


